/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Thready API
 * Threadly learning API with username/password authentication and authenticated post browsing.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  ThreadlyInternalInterfaceDtoAuthResponse,
  ThreadlyInternalInterfaceDtoCommentResponse,
  ThreadlyInternalInterfaceDtoCreateCommentRequest,
  ThreadlyInternalInterfaceDtoCreatePostRequest,
  ThreadlyInternalInterfaceDtoCredentialsRequest,
  ThreadlyInternalInterfaceDtoErrorResponse,
  ThreadlyInternalInterfaceDtoLikeActionResponse,
  ThreadlyInternalInterfaceDtoPostDetailResponse,
  ThreadlyInternalInterfaceDtoPostListResponse,
  ThreadlyInternalInterfaceDtoUpdateCommentRequest,
  ThreadlyInternalInterfaceDtoUpdatePostRequest,
  ThreadlyInternalInterfaceDtoUserResponse,
} from "./threadyAPI.schemas";

import { customInstance } from "../lib/apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPostApiAuthLoginUrl = () => {
  return `/api/auth/login`;
};

/**
 * Authenticate with a username and password, then set an authenticated session cookie.
 * @summary Login
 */
export const postApiAuthLogin = async (
  threadlyInternalInterfaceDtoCredentialsRequest: ThreadlyInternalInterfaceDtoCredentialsRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<ThreadlyInternalInterfaceDtoAuthResponse> => {
  return customInstance<ThreadlyInternalInterfaceDtoAuthResponse>(
    getPostApiAuthLoginUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(threadlyInternalInterfaceDtoCredentialsRequest),
    },
  );
};

export const getPostApiAuthLoginMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthLogin>>,
    TError,
    { data: ThreadlyInternalInterfaceDtoCredentialsRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError,
  { data: ThreadlyInternalInterfaceDtoCredentialsRequest },
  TContext
> => {
  const mutationKey = ["postApiAuthLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthLogin>>,
    { data: ThreadlyInternalInterfaceDtoCredentialsRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthLogin>>
>;
export type PostApiAuthLoginMutationBody =
  ThreadlyInternalInterfaceDtoCredentialsRequest;
export type PostApiAuthLoginMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Login
 */
export const usePostApiAuthLogin = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthLogin>>,
      TError,
      { data: ThreadlyInternalInterfaceDtoCredentialsRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError,
  { data: ThreadlyInternalInterfaceDtoCredentialsRequest },
  TContext
> => {
  return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient);
};

export const getPostApiAuthLogoutUrl = () => {
  return `/api/auth/logout`;
};

/**
 * Clear the authenticated session cookie.
 * @summary Logout
 */
export const postApiAuthLogout = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getPostApiAuthLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getPostApiAuthLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthLogout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postApiAuthLogout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthLogout>>,
    void
  > = () => {
    return postApiAuthLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthLogout>>
>;

export type PostApiAuthLogoutMutationError = unknown;

/**
 * @summary Logout
 */
export const usePostApiAuthLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthLogout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getPostApiAuthLogoutMutationOptions(options), queryClient);
};

export const getPostApiAuthRegisterUrl = () => {
  return `/api/auth/register`;
};

/**
 * Create a user with a username and password, then set an authenticated session cookie.
 * @summary Register a user
 */
export const postApiAuthRegister = async (
  threadlyInternalInterfaceDtoCredentialsRequest: ThreadlyInternalInterfaceDtoCredentialsRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<ThreadlyInternalInterfaceDtoAuthResponse> => {
  return customInstance<ThreadlyInternalInterfaceDtoAuthResponse>(
    getPostApiAuthRegisterUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(threadlyInternalInterfaceDtoCredentialsRequest),
    },
  );
};

export const getPostApiAuthRegisterMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthRegister>>,
    TError,
    { data: ThreadlyInternalInterfaceDtoCredentialsRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthRegister>>,
  TError,
  { data: ThreadlyInternalInterfaceDtoCredentialsRequest },
  TContext
> => {
  const mutationKey = ["postApiAuthRegister"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthRegister>>,
    { data: ThreadlyInternalInterfaceDtoCredentialsRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthRegister>>
>;
export type PostApiAuthRegisterMutationBody =
  ThreadlyInternalInterfaceDtoCredentialsRequest;
export type PostApiAuthRegisterMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Register a user
 */
export const usePostApiAuthRegister = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthRegister>>,
      TError,
      { data: ThreadlyInternalInterfaceDtoCredentialsRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthRegister>>,
  TError,
  { data: ThreadlyInternalInterfaceDtoCredentialsRequest },
  TContext
> => {
  return useMutation(
    getPostApiAuthRegisterMutationOptions(options),
    queryClient,
  );
};

export const getDeleteApiCommentsIdUrl = (id: string) => {
  return `/api/comments/${id}`;
};

/**
 * Soft-delete a comment and its direct replies when the authenticated user is its author.
 * @summary Delete a comment
 */
export const deleteApiCommentsId = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDeleteApiCommentsIdUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteApiCommentsIdMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiCommentsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiCommentsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiCommentsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiCommentsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiCommentsId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiCommentsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiCommentsId>>
>;

export type DeleteApiCommentsIdMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Delete a comment
 */
export const useDeleteApiCommentsId = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiCommentsId>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiCommentsId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteApiCommentsIdMutationOptions(options),
    queryClient,
  );
};

export const getPutApiCommentsIdUrl = (id: string) => {
  return `/api/comments/${id}`;
};

/**
 * Update a comment when the authenticated user is its author.
 * @summary Update a comment
 */
export const putApiCommentsId = async (
  id: string,
  threadlyInternalInterfaceDtoUpdateCommentRequest: ThreadlyInternalInterfaceDtoUpdateCommentRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getPutApiCommentsIdUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(threadlyInternalInterfaceDtoUpdateCommentRequest),
  });
};

export const getPutApiCommentsIdMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiCommentsId>>,
    TError,
    { id: string; data: ThreadlyInternalInterfaceDtoUpdateCommentRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiCommentsId>>,
  TError,
  { id: string; data: ThreadlyInternalInterfaceDtoUpdateCommentRequest },
  TContext
> => {
  const mutationKey = ["putApiCommentsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiCommentsId>>,
    { id: string; data: ThreadlyInternalInterfaceDtoUpdateCommentRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiCommentsId(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiCommentsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiCommentsId>>
>;
export type PutApiCommentsIdMutationBody =
  ThreadlyInternalInterfaceDtoUpdateCommentRequest;
export type PutApiCommentsIdMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Update a comment
 */
export const usePutApiCommentsId = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiCommentsId>>,
      TError,
      { id: string; data: ThreadlyInternalInterfaceDtoUpdateCommentRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiCommentsId>>,
  TError,
  { id: string; data: ThreadlyInternalInterfaceDtoUpdateCommentRequest },
  TContext
> => {
  return useMutation(getPutApiCommentsIdMutationOptions(options), queryClient);
};

export const getDeleteApiCommentsIdLikeUrl = (id: string) => {
  return `/api/comments/${id}/like`;
};

/**
 * Remove the authenticated user's Like from a comment.
 * @summary Unlike a comment
 */
export const deleteApiCommentsIdLike = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<ThreadlyInternalInterfaceDtoLikeActionResponse> => {
  return customInstance<ThreadlyInternalInterfaceDtoLikeActionResponse>(
    getDeleteApiCommentsIdLikeUrl(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getDeleteApiCommentsIdLikeMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiCommentsIdLike>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiCommentsIdLike>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiCommentsIdLike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiCommentsIdLike>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiCommentsIdLike(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiCommentsIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiCommentsIdLike>>
>;

export type DeleteApiCommentsIdLikeMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Unlike a comment
 */
export const useDeleteApiCommentsIdLike = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiCommentsIdLike>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiCommentsIdLike>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteApiCommentsIdLikeMutationOptions(options),
    queryClient,
  );
};

export const getPutApiCommentsIdLikeUrl = (id: string) => {
  return `/api/comments/${id}/like`;
};

/**
 * Create or keep the authenticated user's Like for a comment.
 * @summary Like a comment
 */
export const putApiCommentsIdLike = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<ThreadlyInternalInterfaceDtoLikeActionResponse> => {
  return customInstance<ThreadlyInternalInterfaceDtoLikeActionResponse>(
    getPutApiCommentsIdLikeUrl(id),
    {
      ...options,
      method: "PUT",
    },
  );
};

export const getPutApiCommentsIdLikeMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiCommentsIdLike>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiCommentsIdLike>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["putApiCommentsIdLike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiCommentsIdLike>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return putApiCommentsIdLike(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiCommentsIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiCommentsIdLike>>
>;

export type PutApiCommentsIdLikeMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Like a comment
 */
export const usePutApiCommentsIdLike = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiCommentsIdLike>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiCommentsIdLike>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPutApiCommentsIdLikeMutationOptions(options),
    queryClient,
  );
};

export const getGetApiMeUrl = () => {
  return `/api/me`;
};

/**
 * Return the user represented by the authenticated session cookie.
 * @summary Get current user
 */
export const getApiMe = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<ThreadlyInternalInterfaceDtoUserResponse> => {
  return customInstance<ThreadlyInternalInterfaceDtoUserResponse>(
    getGetApiMeUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiMeQueryKey = () => {
  return [`/api/me`] as const;
};

export const getGetApiMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({
    signal,
  }) => getApiMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiMe>>
>;
export type GetApiMeQueryError = ThreadlyInternalInterfaceDtoErrorResponse;

export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user
 */

export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetApiMeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({
    signal,
  }) => getApiMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiMeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiMe>>
>;
export type GetApiMeSuspenseQueryError =
  ThreadlyInternalInterfaceDtoErrorResponse;

export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user
 */

export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiMeSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetApiPostsUrl = () => {
  return `/api/posts`;
};

/**
 * Get all posts visible to the authenticated user.
 * @summary List posts
 */
export const getApiPosts = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<ThreadlyInternalInterfaceDtoPostListResponse[]> => {
  return customInstance<ThreadlyInternalInterfaceDtoPostListResponse[]>(
    getGetApiPostsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiPostsQueryKey = () => {
  return [`/api/posts`] as const;
};

export const getGetApiPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPosts>>> = ({
    signal,
  }) => getApiPosts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPosts>>
>;
export type GetApiPostsQueryError = ThreadlyInternalInterfaceDtoErrorResponse;

export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPosts>>,
          TError,
          Awaited<ReturnType<typeof getApiPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPosts>>,
          TError,
          Awaited<ReturnType<typeof getApiPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List posts
 */

export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetApiPostsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getApiPosts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPosts>>> = ({
    signal,
  }) => getApiPosts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPosts>>
>;
export type GetApiPostsSuspenseQueryError =
  ThreadlyInternalInterfaceDtoErrorResponse;

export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List posts
 */

export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getPostApiPostsUrl = () => {
  return `/api/posts`;
};

/**
 * Create a post owned by the authenticated user.
 * @summary Create post
 */
export const postApiPosts = async (
  threadlyInternalInterfaceDtoCreatePostRequest: ThreadlyInternalInterfaceDtoCreatePostRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getPostApiPostsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(threadlyInternalInterfaceDtoCreatePostRequest),
  });
};

export const getPostApiPostsMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiPosts>>,
    TError,
    { data: ThreadlyInternalInterfaceDtoCreatePostRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiPosts>>,
  TError,
  { data: ThreadlyInternalInterfaceDtoCreatePostRequest },
  TContext
> => {
  const mutationKey = ["postApiPosts"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiPosts>>,
    { data: ThreadlyInternalInterfaceDtoCreatePostRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiPosts(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiPostsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiPosts>>
>;
export type PostApiPostsMutationBody =
  ThreadlyInternalInterfaceDtoCreatePostRequest;
export type PostApiPostsMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Create post
 */
export const usePostApiPosts = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiPosts>>,
      TError,
      { data: ThreadlyInternalInterfaceDtoCreatePostRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiPosts>>,
  TError,
  { data: ThreadlyInternalInterfaceDtoCreatePostRequest },
  TContext
> => {
  return useMutation(getPostApiPostsMutationOptions(options), queryClient);
};

export const getDeleteApiPostsIdUrl = (id: string) => {
  return `/api/posts/${id}`;
};

/**
 * Delete a post when it is owned by the authenticated user.
 * @summary Delete current user's post
 */
export const deleteApiPostsId = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDeleteApiPostsIdUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteApiPostsIdMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiPostsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiPostsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiPostsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiPostsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiPostsId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiPostsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiPostsId>>
>;

export type DeleteApiPostsIdMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Delete current user's post
 */
export const useDeleteApiPostsId = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiPostsId>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiPostsId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteApiPostsIdMutationOptions(options), queryClient);
};

export const getGetApiPostsIdUrl = (id: string) => {
  return `/api/posts/${id}`;
};

/**
 * Get a post by ID when it is visible to the authenticated user.
 * @summary Get post by ID
 */
export const getApiPostsId = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<ThreadlyInternalInterfaceDtoPostDetailResponse> => {
  return customInstance<ThreadlyInternalInterfaceDtoPostDetailResponse>(
    getGetApiPostsIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiPostsIdQueryKey = (id: string) => {
  return [`/api/posts/${id}`] as const;
};

export const getGetApiPostsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPostsId>>> = ({
    signal,
  }) => getApiPostsId(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPostsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPostsId>>
>;
export type GetApiPostsIdQueryError = ThreadlyInternalInterfaceDtoErrorResponse;

export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get post by ID
 */

export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetApiPostsIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPostsId>>> = ({
    signal,
  }) => getApiPostsId(id, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiPostsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPostsId>>
>;
export type GetApiPostsIdSuspenseQueryError =
  ThreadlyInternalInterfaceDtoErrorResponse;

export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get post by ID
 */

export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsIdSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getPutApiPostsIdUrl = (id: string) => {
  return `/api/posts/${id}`;
};

/**
 * Update a post when it is owned by the authenticated user.
 * @summary Update current user's post
 */
export const putApiPostsId = async (
  id: string,
  threadlyInternalInterfaceDtoUpdatePostRequest: ThreadlyInternalInterfaceDtoUpdatePostRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getPutApiPostsIdUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(threadlyInternalInterfaceDtoUpdatePostRequest),
  });
};

export const getPutApiPostsIdMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiPostsId>>,
    TError,
    { id: string; data: ThreadlyInternalInterfaceDtoUpdatePostRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiPostsId>>,
  TError,
  { id: string; data: ThreadlyInternalInterfaceDtoUpdatePostRequest },
  TContext
> => {
  const mutationKey = ["putApiPostsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiPostsId>>,
    { id: string; data: ThreadlyInternalInterfaceDtoUpdatePostRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiPostsId(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiPostsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiPostsId>>
>;
export type PutApiPostsIdMutationBody =
  ThreadlyInternalInterfaceDtoUpdatePostRequest;
export type PutApiPostsIdMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Update current user's post
 */
export const usePutApiPostsId = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiPostsId>>,
      TError,
      { id: string; data: ThreadlyInternalInterfaceDtoUpdatePostRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiPostsId>>,
  TError,
  { id: string; data: ThreadlyInternalInterfaceDtoUpdatePostRequest },
  TContext
> => {
  return useMutation(getPutApiPostsIdMutationOptions(options), queryClient);
};

export const getGetApiPostsIdCommentsUrl = (id: string) => {
  return `/api/posts/${id}/comments`;
};

/**
 * Get active comments nested by root comment and one-level replies.
 * @summary List comments for a post
 */
export const getApiPostsIdComments = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<ThreadlyInternalInterfaceDtoCommentResponse[]> => {
  return customInstance<ThreadlyInternalInterfaceDtoCommentResponse[]>(
    getGetApiPostsIdCommentsUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiPostsIdCommentsQueryKey = (id: string) => {
  return [`/api/posts/${id}/comments`] as const;
};

export const getGetApiPostsIdCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiPostsIdCommentsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiPostsIdComments>>
  > = ({ signal }) => getApiPostsIdComments(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPostsIdComments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsIdCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPostsIdComments>>
>;
export type GetApiPostsIdCommentsQueryError =
  ThreadlyInternalInterfaceDtoErrorResponse;

export function useGetApiPostsIdComments<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsIdComments>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsIdComments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdComments<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsIdComments>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsIdComments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdComments<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List comments for a post
 */

export function useGetApiPostsIdComments<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsIdCommentsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetApiPostsIdCommentsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiPostsIdCommentsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiPostsIdComments>>
  > = ({ signal }) => getApiPostsIdComments(id, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiPostsIdComments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsIdCommentsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPostsIdComments>>
>;
export type GetApiPostsIdCommentsSuspenseQueryError =
  ThreadlyInternalInterfaceDtoErrorResponse;

export function useGetApiPostsIdCommentsSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdCommentsSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdCommentsSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List comments for a post
 */

export function useGetApiPostsIdCommentsSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsIdCommentsSuspenseQueryOptions(
    id,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getPostApiPostsIdCommentsUrl = (id: string) => {
  return `/api/posts/${id}/comments`;
};

/**
 * Create a root comment or one-level reply for a post.
 * @summary Create a comment
 */
export const postApiPostsIdComments = async (
  id: string,
  threadlyInternalInterfaceDtoCreateCommentRequest: ThreadlyInternalInterfaceDtoCreateCommentRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getPostApiPostsIdCommentsUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(threadlyInternalInterfaceDtoCreateCommentRequest),
  });
};

export const getPostApiPostsIdCommentsMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiPostsIdComments>>,
    TError,
    { id: string; data: ThreadlyInternalInterfaceDtoCreateCommentRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiPostsIdComments>>,
  TError,
  { id: string; data: ThreadlyInternalInterfaceDtoCreateCommentRequest },
  TContext
> => {
  const mutationKey = ["postApiPostsIdComments"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiPostsIdComments>>,
    { id: string; data: ThreadlyInternalInterfaceDtoCreateCommentRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postApiPostsIdComments(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiPostsIdCommentsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiPostsIdComments>>
>;
export type PostApiPostsIdCommentsMutationBody =
  ThreadlyInternalInterfaceDtoCreateCommentRequest;
export type PostApiPostsIdCommentsMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Create a comment
 */
export const usePostApiPostsIdComments = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiPostsIdComments>>,
      TError,
      { id: string; data: ThreadlyInternalInterfaceDtoCreateCommentRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiPostsIdComments>>,
  TError,
  { id: string; data: ThreadlyInternalInterfaceDtoCreateCommentRequest },
  TContext
> => {
  return useMutation(
    getPostApiPostsIdCommentsMutationOptions(options),
    queryClient,
  );
};

export const getDeleteApiPostsIdLikeUrl = (id: string) => {
  return `/api/posts/${id}/like`;
};

/**
 * Remove the authenticated user's Like from a post.
 * @summary Unlike a post
 */
export const deleteApiPostsIdLike = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<ThreadlyInternalInterfaceDtoLikeActionResponse> => {
  return customInstance<ThreadlyInternalInterfaceDtoLikeActionResponse>(
    getDeleteApiPostsIdLikeUrl(id),
    {
      ...options,
      method: "DELETE",
    },
  );
};

export const getDeleteApiPostsIdLikeMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiPostsIdLike>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiPostsIdLike>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiPostsIdLike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiPostsIdLike>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiPostsIdLike(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiPostsIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiPostsIdLike>>
>;

export type DeleteApiPostsIdLikeMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Unlike a post
 */
export const useDeleteApiPostsIdLike = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiPostsIdLike>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiPostsIdLike>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteApiPostsIdLikeMutationOptions(options),
    queryClient,
  );
};

export const getPutApiPostsIdLikeUrl = (id: string) => {
  return `/api/posts/${id}/like`;
};

/**
 * Create or keep the authenticated user's Like for a post.
 * @summary Like a post
 */
export const putApiPostsIdLike = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<ThreadlyInternalInterfaceDtoLikeActionResponse> => {
  return customInstance<ThreadlyInternalInterfaceDtoLikeActionResponse>(
    getPutApiPostsIdLikeUrl(id),
    {
      ...options,
      method: "PUT",
    },
  );
};

export const getPutApiPostsIdLikeMutationOptions = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiPostsIdLike>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiPostsIdLike>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["putApiPostsIdLike"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiPostsIdLike>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return putApiPostsIdLike(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiPostsIdLikeMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiPostsIdLike>>
>;

export type PutApiPostsIdLikeMutationError =
  ThreadlyInternalInterfaceDtoErrorResponse;

/**
 * @summary Like a post
 */
export const usePutApiPostsIdLike = <
  TError = ThreadlyInternalInterfaceDtoErrorResponse,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiPostsIdLike>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiPostsIdLike>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getPutApiPostsIdLikeMutationOptions(options), queryClient);
};
