/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Thready API
 * Threadly learning API with username/password authentication and authenticated post browsing.
 * OpenAPI spec version: 1.0
 */
export interface ThreadlyInternalInterfaceDtoUserResponse {
  createdAt?: string;
  id?: string;
  updatedAt?: string;
  username?: string;
}

export interface ThreadlyInternalInterfaceDtoAuthResponse {
  user?: ThreadlyInternalInterfaceDtoUserResponse;
}

export interface ThreadlyInternalInterfaceDtoPublicUserResponse {
  id?: string;
  username?: string;
}

export interface ThreadlyInternalInterfaceDtoCommentResponse {
  author?: ThreadlyInternalInterfaceDtoPublicUserResponse;
  content?: string;
  createdAt?: string;
  id?: string;
  likeCount?: number;
  likedByMe?: boolean;
  replies?: ThreadlyInternalInterfaceDtoCommentResponse[];
  updatedAt?: string;
}

export interface ThreadlyInternalInterfaceDtoCreateCommentRequest {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  content: string;
  parentId?: string;
}

export interface ThreadlyInternalInterfaceDtoCreatePostRequest {
  content: string;
  title: string;
}

export interface ThreadlyInternalInterfaceDtoCredentialsRequest {
  password: string;
  username: string;
}

export interface ThreadlyInternalInterfaceDtoErrorResponse {
  error?: string;
}

export interface ThreadlyInternalInterfaceDtoLikeActionResponse {
  likeCount?: number;
  likedByMe?: boolean;
  targetId?: string;
}

export interface ThreadlyInternalInterfaceDtoPostDetailResponse {
  author?: ThreadlyInternalInterfaceDtoPublicUserResponse;
  content?: string;
  createdAt?: string;
  id?: string;
  likeCount?: number;
  likedByMe?: boolean;
  title?: string;
  updatedAt?: string;
}

export interface ThreadlyInternalInterfaceDtoPostListResponse {
  author?: ThreadlyInternalInterfaceDtoPublicUserResponse;
  createdAt?: string;
  id?: string;
  likeCount?: number;
  likedByMe?: boolean;
  title?: string;
}

export interface ThreadlyInternalInterfaceDtoUpdateCommentRequest {
  /**
   * @minLength 1
   * @maxLength 1000
   */
  content: string;
}

export interface ThreadlyInternalInterfaceDtoUpdatePostRequest {
  content?: string;
  title?: string;
}
