/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Thready API
 * Threadly learning API with username/password authentication and authenticated post browsing.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  DeleteApiCommentsId400,
  DeleteApiCommentsId401,
  DeleteApiCommentsId404,
  DeleteApiCommentsId500,
  DeleteApiPostsId400,
  DeleteApiPostsId401,
  DeleteApiPostsId404,
  DeleteApiPostsId500,
  GetApiMe401,
  GetApiMe404,
  GetApiMe500,
  GetApiPosts401,
  GetApiPosts500,
  GetApiPostsId400,
  GetApiPostsId401,
  GetApiPostsId404,
  GetApiPostsId500,
  GetApiPostsIdComments400,
  GetApiPostsIdComments401,
  GetApiPostsIdComments404,
  GetApiPostsIdComments500,
  InternalInterfaceControllersAuthResponse,
  InternalInterfaceControllersCommentResponse,
  InternalInterfaceControllersCreateCommentRequest,
  InternalInterfaceControllersCreatePostRequest,
  InternalInterfaceControllersCredentialsRequest,
  InternalInterfaceControllersPostDetailResponse,
  InternalInterfaceControllersPostListResponse,
  InternalInterfaceControllersUpdateCommentRequest,
  InternalInterfaceControllersUpdatePostRequest,
  InternalInterfaceControllersUserResponse,
  PostApiAuthLogin400,
  PostApiAuthLogin401,
  PostApiAuthLogin500,
  PostApiAuthRegister400,
  PostApiAuthRegister409,
  PostApiAuthRegister500,
  PostApiPosts400,
  PostApiPosts401,
  PostApiPosts500,
  PostApiPostsIdComments400,
  PostApiPostsIdComments401,
  PostApiPostsIdComments404,
  PostApiPostsIdComments500,
  PutApiCommentsId400,
  PutApiCommentsId401,
  PutApiCommentsId404,
  PutApiCommentsId500,
  PutApiPostsId400,
  PutApiPostsId401,
  PutApiPostsId404,
  PutApiPostsId500,
} from "./threadyAPI.schemas";

import { customInstance } from "../lib/apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPostApiAuthLoginUrl = () => {
  return `/api/auth/login`;
};

/**
 * Authenticate with a username and password, then set an authenticated session cookie.
 * @summary Login
 */
export const postApiAuthLogin = async (
  internalInterfaceControllersCredentialsRequest: InternalInterfaceControllersCredentialsRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<InternalInterfaceControllersAuthResponse> => {
  return customInstance<InternalInterfaceControllersAuthResponse>(
    getPostApiAuthLoginUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(internalInterfaceControllersCredentialsRequest),
    },
  );
};

export const getPostApiAuthLoginMutationOptions = <
  TError = PostApiAuthLogin400 | PostApiAuthLogin401 | PostApiAuthLogin500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthLogin>>,
    TError,
    { data: InternalInterfaceControllersCredentialsRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError,
  { data: InternalInterfaceControllersCredentialsRequest },
  TContext
> => {
  const mutationKey = ["postApiAuthLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthLogin>>,
    { data: InternalInterfaceControllersCredentialsRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthLogin>>
>;
export type PostApiAuthLoginMutationBody =
  InternalInterfaceControllersCredentialsRequest;
export type PostApiAuthLoginMutationError =
  PostApiAuthLogin400 | PostApiAuthLogin401 | PostApiAuthLogin500;

/**
 * @summary Login
 */
export const usePostApiAuthLogin = <
  TError = PostApiAuthLogin400 | PostApiAuthLogin401 | PostApiAuthLogin500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthLogin>>,
      TError,
      { data: InternalInterfaceControllersCredentialsRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError,
  { data: InternalInterfaceControllersCredentialsRequest },
  TContext
> => {
  return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient);
};

export const getPostApiAuthLogoutUrl = () => {
  return `/api/auth/logout`;
};

/**
 * Clear the authenticated session cookie.
 * @summary Logout
 */
export const postApiAuthLogout = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getPostApiAuthLogoutUrl(), {
    ...options,
    method: "POST",
  });
};

export const getPostApiAuthLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthLogout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["postApiAuthLogout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthLogout>>,
    void
  > = () => {
    return postApiAuthLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthLogout>>
>;

export type PostApiAuthLogoutMutationError = unknown;

/**
 * @summary Logout
 */
export const usePostApiAuthLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthLogout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getPostApiAuthLogoutMutationOptions(options), queryClient);
};

export const getPostApiAuthRegisterUrl = () => {
  return `/api/auth/register`;
};

/**
 * Create a user with a username and password, then set an authenticated session cookie.
 * @summary Register a user
 */
export const postApiAuthRegister = async (
  internalInterfaceControllersCredentialsRequest: InternalInterfaceControllersCredentialsRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<InternalInterfaceControllersAuthResponse> => {
  return customInstance<InternalInterfaceControllersAuthResponse>(
    getPostApiAuthRegisterUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(internalInterfaceControllersCredentialsRequest),
    },
  );
};

export const getPostApiAuthRegisterMutationOptions = <
  TError =
    PostApiAuthRegister400 | PostApiAuthRegister409 | PostApiAuthRegister500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthRegister>>,
    TError,
    { data: InternalInterfaceControllersCredentialsRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthRegister>>,
  TError,
  { data: InternalInterfaceControllersCredentialsRequest },
  TContext
> => {
  const mutationKey = ["postApiAuthRegister"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthRegister>>,
    { data: InternalInterfaceControllersCredentialsRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthRegister>>
>;
export type PostApiAuthRegisterMutationBody =
  InternalInterfaceControllersCredentialsRequest;
export type PostApiAuthRegisterMutationError =
  PostApiAuthRegister400 | PostApiAuthRegister409 | PostApiAuthRegister500;

/**
 * @summary Register a user
 */
export const usePostApiAuthRegister = <
  TError =
    PostApiAuthRegister400 | PostApiAuthRegister409 | PostApiAuthRegister500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthRegister>>,
      TError,
      { data: InternalInterfaceControllersCredentialsRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthRegister>>,
  TError,
  { data: InternalInterfaceControllersCredentialsRequest },
  TContext
> => {
  return useMutation(
    getPostApiAuthRegisterMutationOptions(options),
    queryClient,
  );
};

export const getDeleteApiCommentsIdUrl = (id: string) => {
  return `/api/comments/${id}`;
};

/**
 * Soft-delete a comment and its direct replies when the authenticated user is its author.
 * @summary Delete a comment
 */
export const deleteApiCommentsId = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDeleteApiCommentsIdUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteApiCommentsIdMutationOptions = <
  TError =
    | DeleteApiCommentsId400
    | DeleteApiCommentsId401
    | DeleteApiCommentsId404
    | DeleteApiCommentsId500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiCommentsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiCommentsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiCommentsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiCommentsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiCommentsId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiCommentsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiCommentsId>>
>;

export type DeleteApiCommentsIdMutationError =
  | DeleteApiCommentsId400
  | DeleteApiCommentsId401
  | DeleteApiCommentsId404
  | DeleteApiCommentsId500;

/**
 * @summary Delete a comment
 */
export const useDeleteApiCommentsId = <
  TError =
    | DeleteApiCommentsId400
    | DeleteApiCommentsId401
    | DeleteApiCommentsId404
    | DeleteApiCommentsId500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiCommentsId>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiCommentsId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getDeleteApiCommentsIdMutationOptions(options),
    queryClient,
  );
};

export const getPutApiCommentsIdUrl = (id: string) => {
  return `/api/comments/${id}`;
};

/**
 * Update a comment when the authenticated user is its author.
 * @summary Update a comment
 */
export const putApiCommentsId = async (
  id: string,
  internalInterfaceControllersUpdateCommentRequest: InternalInterfaceControllersUpdateCommentRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getPutApiCommentsIdUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(internalInterfaceControllersUpdateCommentRequest),
  });
};

export const getPutApiCommentsIdMutationOptions = <
  TError =
    | PutApiCommentsId400
    | PutApiCommentsId401
    | PutApiCommentsId404
    | PutApiCommentsId500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiCommentsId>>,
    TError,
    { id: string; data: InternalInterfaceControllersUpdateCommentRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiCommentsId>>,
  TError,
  { id: string; data: InternalInterfaceControllersUpdateCommentRequest },
  TContext
> => {
  const mutationKey = ["putApiCommentsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiCommentsId>>,
    { id: string; data: InternalInterfaceControllersUpdateCommentRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiCommentsId(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiCommentsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiCommentsId>>
>;
export type PutApiCommentsIdMutationBody =
  InternalInterfaceControllersUpdateCommentRequest;
export type PutApiCommentsIdMutationError =
  | PutApiCommentsId400
  | PutApiCommentsId401
  | PutApiCommentsId404
  | PutApiCommentsId500;

/**
 * @summary Update a comment
 */
export const usePutApiCommentsId = <
  TError =
    | PutApiCommentsId400
    | PutApiCommentsId401
    | PutApiCommentsId404
    | PutApiCommentsId500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiCommentsId>>,
      TError,
      { id: string; data: InternalInterfaceControllersUpdateCommentRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiCommentsId>>,
  TError,
  { id: string; data: InternalInterfaceControllersUpdateCommentRequest },
  TContext
> => {
  return useMutation(getPutApiCommentsIdMutationOptions(options), queryClient);
};

export const getGetApiMeUrl = () => {
  return `/api/me`;
};

/**
 * Return the user represented by the authenticated session cookie.
 * @summary Get current user
 */
export const getApiMe = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<InternalInterfaceControllersUserResponse> => {
  return customInstance<InternalInterfaceControllersUserResponse>(
    getGetApiMeUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiMeQueryKey = () => {
  return [`/api/me`] as const;
};

export const getGetApiMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({
    signal,
  }) => getApiMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiMe>>
>;
export type GetApiMeQueryError = GetApiMe401 | GetApiMe404 | GetApiMe500;

export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user
 */

export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetApiMeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({
    signal,
  }) => getApiMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiMeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiMe>>
>;
export type GetApiMeSuspenseQueryError =
  GetApiMe401 | GetApiMe404 | GetApiMe500;

export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user
 */

export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiMeSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetApiPostsUrl = () => {
  return `/api/posts`;
};

/**
 * Get all posts visible to the authenticated user.
 * @summary List posts
 */
export const getApiPosts = async (
  options?: Parameters<typeof customInstance>[1],
): Promise<InternalInterfaceControllersPostListResponse[]> => {
  return customInstance<InternalInterfaceControllersPostListResponse[]>(
    getGetApiPostsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiPostsQueryKey = () => {
  return [`/api/posts`] as const;
};

export const getGetApiPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPosts>>> = ({
    signal,
  }) => getApiPosts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPosts>>
>;
export type GetApiPostsQueryError = GetApiPosts401 | GetApiPosts500;

export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPosts>>,
          TError,
          Awaited<ReturnType<typeof getApiPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPosts>>,
          TError,
          Awaited<ReturnType<typeof getApiPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List posts
 */

export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetApiPostsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getApiPosts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPosts>>> = ({
    signal,
  }) => getApiPosts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPosts>>
>;
export type GetApiPostsSuspenseQueryError = GetApiPosts401 | GetApiPosts500;

export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List posts
 */

export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getPostApiPostsUrl = () => {
  return `/api/posts`;
};

/**
 * Create a post owned by the authenticated user.
 * @summary Create post
 */
export const postApiPosts = async (
  internalInterfaceControllersCreatePostRequest: InternalInterfaceControllersCreatePostRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getPostApiPostsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(internalInterfaceControllersCreatePostRequest),
  });
};

export const getPostApiPostsMutationOptions = <
  TError = PostApiPosts400 | PostApiPosts401 | PostApiPosts500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiPosts>>,
    TError,
    { data: InternalInterfaceControllersCreatePostRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiPosts>>,
  TError,
  { data: InternalInterfaceControllersCreatePostRequest },
  TContext
> => {
  const mutationKey = ["postApiPosts"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiPosts>>,
    { data: InternalInterfaceControllersCreatePostRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiPosts(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiPostsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiPosts>>
>;
export type PostApiPostsMutationBody =
  InternalInterfaceControllersCreatePostRequest;
export type PostApiPostsMutationError =
  PostApiPosts400 | PostApiPosts401 | PostApiPosts500;

/**
 * @summary Create post
 */
export const usePostApiPosts = <
  TError = PostApiPosts400 | PostApiPosts401 | PostApiPosts500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiPosts>>,
      TError,
      { data: InternalInterfaceControllersCreatePostRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiPosts>>,
  TError,
  { data: InternalInterfaceControllersCreatePostRequest },
  TContext
> => {
  return useMutation(getPostApiPostsMutationOptions(options), queryClient);
};

export const getDeleteApiPostsIdUrl = (id: string) => {
  return `/api/posts/${id}`;
};

/**
 * Delete a post when it is owned by the authenticated user.
 * @summary Delete current user's post
 */
export const deleteApiPostsId = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getDeleteApiPostsIdUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteApiPostsIdMutationOptions = <
  TError =
    | DeleteApiPostsId400
    | DeleteApiPostsId401
    | DeleteApiPostsId404
    | DeleteApiPostsId500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiPostsId>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiPostsId>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["deleteApiPostsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiPostsId>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiPostsId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiPostsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiPostsId>>
>;

export type DeleteApiPostsIdMutationError =
  | DeleteApiPostsId400
  | DeleteApiPostsId401
  | DeleteApiPostsId404
  | DeleteApiPostsId500;

/**
 * @summary Delete current user's post
 */
export const useDeleteApiPostsId = <
  TError =
    | DeleteApiPostsId400
    | DeleteApiPostsId401
    | DeleteApiPostsId404
    | DeleteApiPostsId500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiPostsId>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiPostsId>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(getDeleteApiPostsIdMutationOptions(options), queryClient);
};

export const getGetApiPostsIdUrl = (id: string) => {
  return `/api/posts/${id}`;
};

/**
 * Get a post by ID when it is visible to the authenticated user.
 * @summary Get post by ID
 */
export const getApiPostsId = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<InternalInterfaceControllersPostDetailResponse> => {
  return customInstance<InternalInterfaceControllersPostDetailResponse>(
    getGetApiPostsIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiPostsIdQueryKey = (id: string) => {
  return [`/api/posts/${id}`] as const;
};

export const getGetApiPostsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPostsId>>> = ({
    signal,
  }) => getApiPostsId(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPostsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPostsId>>
>;
export type GetApiPostsIdQueryError =
  GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500;

export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get post by ID
 */

export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetApiPostsIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPostsId>>> = ({
    signal,
  }) => getApiPostsId(id, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiPostsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPostsId>>
>;
export type GetApiPostsIdSuspenseQueryError =
  GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500;

export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get post by ID
 */

export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    GetApiPostsId400 | GetApiPostsId401 | GetApiPostsId404 | GetApiPostsId500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsIdSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getPutApiPostsIdUrl = (id: string) => {
  return `/api/posts/${id}`;
};

/**
 * Update a post when it is owned by the authenticated user.
 * @summary Update current user's post
 */
export const putApiPostsId = async (
  id: string,
  internalInterfaceControllersUpdatePostRequest: InternalInterfaceControllersUpdatePostRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getPutApiPostsIdUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(internalInterfaceControllersUpdatePostRequest),
  });
};

export const getPutApiPostsIdMutationOptions = <
  TError =
    PutApiPostsId400 | PutApiPostsId401 | PutApiPostsId404 | PutApiPostsId500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiPostsId>>,
    TError,
    { id: string; data: InternalInterfaceControllersUpdatePostRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiPostsId>>,
  TError,
  { id: string; data: InternalInterfaceControllersUpdatePostRequest },
  TContext
> => {
  const mutationKey = ["putApiPostsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiPostsId>>,
    { id: string; data: InternalInterfaceControllersUpdatePostRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiPostsId(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiPostsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiPostsId>>
>;
export type PutApiPostsIdMutationBody =
  InternalInterfaceControllersUpdatePostRequest;
export type PutApiPostsIdMutationError =
  PutApiPostsId400 | PutApiPostsId401 | PutApiPostsId404 | PutApiPostsId500;

/**
 * @summary Update current user's post
 */
export const usePutApiPostsId = <
  TError =
    PutApiPostsId400 | PutApiPostsId401 | PutApiPostsId404 | PutApiPostsId500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiPostsId>>,
      TError,
      { id: string; data: InternalInterfaceControllersUpdatePostRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiPostsId>>,
  TError,
  { id: string; data: InternalInterfaceControllersUpdatePostRequest },
  TContext
> => {
  return useMutation(getPutApiPostsIdMutationOptions(options), queryClient);
};

export const getGetApiPostsIdCommentsUrl = (id: string) => {
  return `/api/posts/${id}/comments`;
};

/**
 * Get active comments nested by root comment and one-level replies.
 * @summary List comments for a post
 */
export const getApiPostsIdComments = async (
  id: string,
  options?: Parameters<typeof customInstance>[1],
): Promise<InternalInterfaceControllersCommentResponse[]> => {
  return customInstance<InternalInterfaceControllersCommentResponse[]>(
    getGetApiPostsIdCommentsUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiPostsIdCommentsQueryKey = (id: string) => {
  return [`/api/posts/${id}/comments`] as const;
};

export const getGetApiPostsIdCommentsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError =
    | GetApiPostsIdComments400
    | GetApiPostsIdComments401
    | GetApiPostsIdComments404
    | GetApiPostsIdComments500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiPostsIdCommentsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiPostsIdComments>>
  > = ({ signal }) => getApiPostsIdComments(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPostsIdComments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsIdCommentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPostsIdComments>>
>;
export type GetApiPostsIdCommentsQueryError =
  | GetApiPostsIdComments400
  | GetApiPostsIdComments401
  | GetApiPostsIdComments404
  | GetApiPostsIdComments500;

export function useGetApiPostsIdComments<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError =
    | GetApiPostsIdComments400
    | GetApiPostsIdComments401
    | GetApiPostsIdComments404
    | GetApiPostsIdComments500,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsIdComments>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsIdComments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdComments<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError =
    | GetApiPostsIdComments400
    | GetApiPostsIdComments401
    | GetApiPostsIdComments404
    | GetApiPostsIdComments500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsIdComments>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsIdComments>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdComments<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError =
    | GetApiPostsIdComments400
    | GetApiPostsIdComments401
    | GetApiPostsIdComments404
    | GetApiPostsIdComments500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List comments for a post
 */

export function useGetApiPostsIdComments<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError =
    | GetApiPostsIdComments400
    | GetApiPostsIdComments401
    | GetApiPostsIdComments404
    | GetApiPostsIdComments500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsIdCommentsQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getGetApiPostsIdCommentsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError =
    | GetApiPostsIdComments400
    | GetApiPostsIdComments401
    | GetApiPostsIdComments404
    | GetApiPostsIdComments500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetApiPostsIdCommentsQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getApiPostsIdComments>>
  > = ({ signal }) => getApiPostsIdComments(id, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiPostsIdComments>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsIdCommentsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPostsIdComments>>
>;
export type GetApiPostsIdCommentsSuspenseQueryError =
  | GetApiPostsIdComments400
  | GetApiPostsIdComments401
  | GetApiPostsIdComments404
  | GetApiPostsIdComments500;

export function useGetApiPostsIdCommentsSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError =
    | GetApiPostsIdComments400
    | GetApiPostsIdComments401
    | GetApiPostsIdComments404
    | GetApiPostsIdComments500,
>(
  id: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdCommentsSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError =
    | GetApiPostsIdComments400
    | GetApiPostsIdComments401
    | GetApiPostsIdComments404
    | GetApiPostsIdComments500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdCommentsSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError =
    | GetApiPostsIdComments400
    | GetApiPostsIdComments401
    | GetApiPostsIdComments404
    | GetApiPostsIdComments500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List comments for a post
 */

export function useGetApiPostsIdCommentsSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsIdComments>>,
  TError =
    | GetApiPostsIdComments400
    | GetApiPostsIdComments401
    | GetApiPostsIdComments404
    | GetApiPostsIdComments500,
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsIdComments>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsIdCommentsSuspenseQueryOptions(
    id,
    options,
  );

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getPostApiPostsIdCommentsUrl = (id: string) => {
  return `/api/posts/${id}/comments`;
};

/**
 * Create a root comment or one-level reply for a post.
 * @summary Create a comment
 */
export const postApiPostsIdComments = async (
  id: string,
  internalInterfaceControllersCreateCommentRequest: InternalInterfaceControllersCreateCommentRequest,
  options?: Parameters<typeof customInstance>[1],
): Promise<void> => {
  return customInstance<void>(getPostApiPostsIdCommentsUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(internalInterfaceControllersCreateCommentRequest),
  });
};

export const getPostApiPostsIdCommentsMutationOptions = <
  TError =
    | PostApiPostsIdComments400
    | PostApiPostsIdComments401
    | PostApiPostsIdComments404
    | PostApiPostsIdComments500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiPostsIdComments>>,
    TError,
    { id: string; data: InternalInterfaceControllersCreateCommentRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiPostsIdComments>>,
  TError,
  { id: string; data: InternalInterfaceControllersCreateCommentRequest },
  TContext
> => {
  const mutationKey = ["postApiPostsIdComments"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiPostsIdComments>>,
    { id: string; data: InternalInterfaceControllersCreateCommentRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return postApiPostsIdComments(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiPostsIdCommentsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiPostsIdComments>>
>;
export type PostApiPostsIdCommentsMutationBody =
  InternalInterfaceControllersCreateCommentRequest;
export type PostApiPostsIdCommentsMutationError =
  | PostApiPostsIdComments400
  | PostApiPostsIdComments401
  | PostApiPostsIdComments404
  | PostApiPostsIdComments500;

/**
 * @summary Create a comment
 */
export const usePostApiPostsIdComments = <
  TError =
    | PostApiPostsIdComments400
    | PostApiPostsIdComments401
    | PostApiPostsIdComments404
    | PostApiPostsIdComments500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiPostsIdComments>>,
      TError,
      { id: string; data: InternalInterfaceControllersCreateCommentRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiPostsIdComments>>,
  TError,
  { id: string; data: InternalInterfaceControllersCreateCommentRequest },
  TContext
> => {
  return useMutation(
    getPostApiPostsIdCommentsMutationOptions(options),
    queryClient,
  );
};
