/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Thready API
 * Threadly learning API with username/password authentication and authenticated post browsing.
 * OpenAPI spec version: 1.0
 */
export interface InternalInterfaceControllersCreatePostRequest {
  content: string;
  title: string;
}

export interface InternalInterfaceControllersUpdatePostRequest {
  content?: string;
  title?: string;
}

export interface InternalInterfaceControllersUserResponse {
  createdAt?: string;
  id?: number;
  updatedAt?: string;
  username?: string;
}

export interface InternalInterfaceControllersAuthResponse {
  user?: InternalInterfaceControllersUserResponse;
}

export interface InternalInterfaceControllersCredentialsRequest {
  password: string;
  username: string;
}

export interface InternalInterfaceControllersPostAuthorResponse {
  id?: number;
  username?: string;
}

export interface InternalInterfaceControllersPostDetailResponse {
  author?: InternalInterfaceControllersPostAuthorResponse;
  content?: string;
  createdAt?: string;
  id?: number;
  title?: string;
  updatedAt?: string;
}

export interface InternalInterfaceControllersPostListResponse {
  author?: InternalInterfaceControllersPostAuthorResponse;
  createdAt?: string;
  id?: number;
  title?: string;
}

export type PostApiAuthLogin400 = { [key: string]: unknown };

export type PostApiAuthLogin401 = { [key: string]: unknown };

export type PostApiAuthLogin500 = { [key: string]: unknown };

export type PostApiAuthRegister400 = { [key: string]: unknown };

export type PostApiAuthRegister409 = { [key: string]: unknown };

export type PostApiAuthRegister500 = { [key: string]: unknown };

export type GetApiMe401 = { [key: string]: unknown };

export type GetApiMe404 = { [key: string]: unknown };

export type GetApiMe500 = { [key: string]: unknown };

export type GetApiPosts401 = { [key: string]: unknown };

export type GetApiPosts500 = { [key: string]: unknown };

export type PostApiPosts400 = { [key: string]: unknown };

export type PostApiPosts401 = { [key: string]: unknown };

export type PostApiPosts500 = { [key: string]: unknown };

export type DeleteApiPostsId400 = { [key: string]: unknown };

export type DeleteApiPostsId401 = { [key: string]: unknown };

export type DeleteApiPostsId404 = { [key: string]: unknown };

export type DeleteApiPostsId500 = { [key: string]: unknown };

export type GetApiPostsId400 = { [key: string]: unknown };

export type GetApiPostsId401 = { [key: string]: unknown };

export type GetApiPostsId404 = { [key: string]: unknown };

export type GetApiPostsId500 = { [key: string]: unknown };

export type PutApiPostsId400 = { [key: string]: unknown };

export type PutApiPostsId401 = { [key: string]: unknown };

export type PutApiPostsId404 = { [key: string]: unknown };

export type PutApiPostsId500 = { [key: string]: unknown };
