/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Thready API
 * OpenAPI spec version: 1.0
 */
export interface GormDeletedAt {
  time?: string;
  /** Valid is true if Time is not NULL */
  valid?: boolean;
}

export interface ThreadlyInternalDomainModelsPost {
  content?: string;
  createdAt?: string;
  deletedAt?: GormDeletedAt;
  id?: number;
  title?: string;
  updatedAt?: string;
}

export interface GinH {
  [key: string]: unknown;
}

export interface InternalInterfaceControllersCreatePostRequest {
  content: string;
  title: string;
}

export interface InternalInterfaceControllersUpdatePostRequest {
  content?: string;
  title?: string;
}
