/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Thready API
 * Threadly learning API with username/password authentication and authenticated post browsing.
 * OpenAPI spec version: 1.0
 */
import { useMutation, useQuery, useSuspenseQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from "@tanstack/react-query";

import type {
  DeleteApiPostsId400,
  DeleteApiPostsId401,
  DeleteApiPostsId404,
  DeleteApiPostsId500,
  GetApiMe401,
  GetApiMe404,
  GetApiMe500,
  GetApiPosts401,
  GetApiPosts500,
  GetApiPostsId400,
  GetApiPostsId401,
  GetApiPostsId404,
  GetApiPostsId500,
  InternalInterfaceControllersAuthResponse,
  InternalInterfaceControllersCreatePostRequest,
  InternalInterfaceControllersCredentialsRequest,
  InternalInterfaceControllersPostDetailResponse,
  InternalInterfaceControllersPostListResponse,
  InternalInterfaceControllersUpdatePostRequest,
  InternalInterfaceControllersUserResponse,
  PostApiAuthLogin400,
  PostApiAuthLogin401,
  PostApiAuthLogin500,
  PostApiAuthRegister400,
  PostApiAuthRegister409,
  PostApiAuthRegister500,
  PostApiPosts400,
  PostApiPosts401,
  PostApiPosts500,
  PutApiPostsId400,
  PutApiPostsId401,
  PutApiPostsId404,
  PutApiPostsId500,
} from "./threadyAPI.schemas";

import { customInstance } from "../lib/apiClient";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Authenticate with a username and password, then issue a JWT access token.
 * @summary Login
 */
export const getPostApiAuthLoginUrl = () => {
  return `/api/auth/login`;
};

export const postApiAuthLogin = async (
  internalInterfaceControllersCredentialsRequest: InternalInterfaceControllersCredentialsRequest,
  options?: RequestInit,
): Promise<InternalInterfaceControllersAuthResponse> => {
  return customInstance<InternalInterfaceControllersAuthResponse>(
    getPostApiAuthLoginUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(internalInterfaceControllersCredentialsRequest),
    },
  );
};

export const getPostApiAuthLoginMutationOptions = <
  TError = PostApiAuthLogin400 | PostApiAuthLogin401 | PostApiAuthLogin500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthLogin>>,
    TError,
    { data: InternalInterfaceControllersCredentialsRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError,
  { data: InternalInterfaceControllersCredentialsRequest },
  TContext
> => {
  const mutationKey = ["postApiAuthLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthLogin>>,
    { data: InternalInterfaceControllersCredentialsRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthLogin>>
>;
export type PostApiAuthLoginMutationBody =
  InternalInterfaceControllersCredentialsRequest;
export type PostApiAuthLoginMutationError =
  | PostApiAuthLogin400
  | PostApiAuthLogin401
  | PostApiAuthLogin500;

/**
 * @summary Login
 */
export const usePostApiAuthLogin = <
  TError = PostApiAuthLogin400 | PostApiAuthLogin401 | PostApiAuthLogin500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthLogin>>,
      TError,
      { data: InternalInterfaceControllersCredentialsRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthLogin>>,
  TError,
  { data: InternalInterfaceControllersCredentialsRequest },
  TContext
> => {
  return useMutation(getPostApiAuthLoginMutationOptions(options), queryClient);
};

/**
 * Create a user with a username and password, then issue a JWT access token.
 * @summary Register a user
 */
export const getPostApiAuthRegisterUrl = () => {
  return `/api/auth/register`;
};

export const postApiAuthRegister = async (
  internalInterfaceControllersCredentialsRequest: InternalInterfaceControllersCredentialsRequest,
  options?: RequestInit,
): Promise<InternalInterfaceControllersAuthResponse> => {
  return customInstance<InternalInterfaceControllersAuthResponse>(
    getPostApiAuthRegisterUrl(),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(internalInterfaceControllersCredentialsRequest),
    },
  );
};

export const getPostApiAuthRegisterMutationOptions = <
  TError =
    | PostApiAuthRegister400
    | PostApiAuthRegister409
    | PostApiAuthRegister500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiAuthRegister>>,
    TError,
    { data: InternalInterfaceControllersCredentialsRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiAuthRegister>>,
  TError,
  { data: InternalInterfaceControllersCredentialsRequest },
  TContext
> => {
  const mutationKey = ["postApiAuthRegister"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiAuthRegister>>,
    { data: InternalInterfaceControllersCredentialsRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiAuthRegister(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiAuthRegister>>
>;
export type PostApiAuthRegisterMutationBody =
  InternalInterfaceControllersCredentialsRequest;
export type PostApiAuthRegisterMutationError =
  | PostApiAuthRegister400
  | PostApiAuthRegister409
  | PostApiAuthRegister500;

/**
 * @summary Register a user
 */
export const usePostApiAuthRegister = <
  TError =
    | PostApiAuthRegister400
    | PostApiAuthRegister409
    | PostApiAuthRegister500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiAuthRegister>>,
      TError,
      { data: InternalInterfaceControllersCredentialsRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiAuthRegister>>,
  TError,
  { data: InternalInterfaceControllersCredentialsRequest },
  TContext
> => {
  return useMutation(
    getPostApiAuthRegisterMutationOptions(options),
    queryClient,
  );
};

/**
 * Return the user represented by the Bearer JWT.
 * @summary Get current user
 */
export const getGetApiMeUrl = () => {
  return `/api/me`;
};

export const getApiMe = async (
  options?: RequestInit,
): Promise<InternalInterfaceControllersUserResponse> => {
  return customInstance<InternalInterfaceControllersUserResponse>(
    getGetApiMeUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiMeQueryKey = () => {
  return [`/api/me`] as const;
};

export const getGetApiMeQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({
    signal,
  }) => getApiMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiMe>>
>;
export type GetApiMeQueryError = GetApiMe401 | GetApiMe404 | GetApiMe500;

export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiMe>>,
          TError,
          Awaited<ReturnType<typeof getApiMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user
 */

export function useGetApiMe<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetApiMeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<Awaited<ReturnType<typeof getApiMe>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiMeQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiMe>>> = ({
    signal,
  }) => getApiMe({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiMeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiMe>>
>;
export type GetApiMeSuspenseQueryError =
  | GetApiMe401
  | GetApiMe404
  | GetApiMe500;

export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get current user
 */

export function useGetApiMeSuspense<
  TData = Awaited<ReturnType<typeof getApiMe>>,
  TError = GetApiMe401 | GetApiMe404 | GetApiMe500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiMeSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Get all posts visible to the authenticated user.
 * @summary List posts
 */
export const getGetApiPostsUrl = () => {
  return `/api/posts`;
};

export const getApiPosts = async (
  options?: RequestInit,
): Promise<InternalInterfaceControllersPostListResponse[]> => {
  return customInstance<InternalInterfaceControllersPostListResponse[]>(
    getGetApiPostsUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiPostsQueryKey = () => {
  return [`/api/posts`] as const;
};

export const getGetApiPostsQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPosts>>> = ({
    signal,
  }) => getApiPosts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPosts>>
>;
export type GetApiPostsQueryError = GetApiPosts401 | GetApiPosts500;

export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPosts>>,
          TError,
          Awaited<ReturnType<typeof getApiPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPosts>>,
          TError,
          Awaited<ReturnType<typeof getApiPosts>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List posts
 */

export function useGetApiPosts<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPosts>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetApiPostsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getApiPosts>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPosts>>> = ({
    signal,
  }) => getApiPosts({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiPosts>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPosts>>
>;
export type GetApiPostsSuspenseQueryError = GetApiPosts401 | GetApiPosts500;

export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List posts
 */

export function useGetApiPostsSuspense<
  TData = Awaited<ReturnType<typeof getApiPosts>>,
  TError = GetApiPosts401 | GetApiPosts500,
>(
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPosts>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create a post owned by the authenticated user.
 * @summary Create post
 */
export const getPostApiPostsUrl = () => {
  return `/api/posts`;
};

export const postApiPosts = async (
  internalInterfaceControllersCreatePostRequest: InternalInterfaceControllersCreatePostRequest,
  options?: RequestInit,
): Promise<void> => {
  return customInstance<void>(getPostApiPostsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(internalInterfaceControllersCreatePostRequest),
  });
};

export const getPostApiPostsMutationOptions = <
  TError = PostApiPosts400 | PostApiPosts401 | PostApiPosts500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postApiPosts>>,
    TError,
    { data: InternalInterfaceControllersCreatePostRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postApiPosts>>,
  TError,
  { data: InternalInterfaceControllersCreatePostRequest },
  TContext
> => {
  const mutationKey = ["postApiPosts"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postApiPosts>>,
    { data: InternalInterfaceControllersCreatePostRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postApiPosts(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostApiPostsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postApiPosts>>
>;
export type PostApiPostsMutationBody =
  InternalInterfaceControllersCreatePostRequest;
export type PostApiPostsMutationError =
  | PostApiPosts400
  | PostApiPosts401
  | PostApiPosts500;

/**
 * @summary Create post
 */
export const usePostApiPosts = <
  TError = PostApiPosts400 | PostApiPosts401 | PostApiPosts500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postApiPosts>>,
      TError,
      { data: InternalInterfaceControllersCreatePostRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postApiPosts>>,
  TError,
  { data: InternalInterfaceControllersCreatePostRequest },
  TContext
> => {
  return useMutation(getPostApiPostsMutationOptions(options), queryClient);
};

/**
 * Delete a post when it is owned by the authenticated user.
 * @summary Delete current user's post
 */
export const getDeleteApiPostsIdUrl = (id: number) => {
  return `/api/posts/${id}`;
};

export const deleteApiPostsId = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customInstance<void>(getDeleteApiPostsIdUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteApiPostsIdMutationOptions = <
  TError =
    | DeleteApiPostsId400
    | DeleteApiPostsId401
    | DeleteApiPostsId404
    | DeleteApiPostsId500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteApiPostsId>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteApiPostsId>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteApiPostsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteApiPostsId>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteApiPostsId(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteApiPostsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteApiPostsId>>
>;

export type DeleteApiPostsIdMutationError =
  | DeleteApiPostsId400
  | DeleteApiPostsId401
  | DeleteApiPostsId404
  | DeleteApiPostsId500;

/**
 * @summary Delete current user's post
 */
export const useDeleteApiPostsId = <
  TError =
    | DeleteApiPostsId400
    | DeleteApiPostsId401
    | DeleteApiPostsId404
    | DeleteApiPostsId500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteApiPostsId>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteApiPostsId>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteApiPostsIdMutationOptions(options), queryClient);
};

/**
 * Get a post by ID when it is visible to the authenticated user.
 * @summary Get post by ID
 */
export const getGetApiPostsIdUrl = (id: number) => {
  return `/api/posts/${id}`;
};

export const getApiPostsId = async (
  id: number,
  options?: RequestInit,
): Promise<InternalInterfaceControllersPostDetailResponse> => {
  return customInstance<InternalInterfaceControllersPostDetailResponse>(
    getGetApiPostsIdUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetApiPostsIdQueryKey = (id: number) => {
  return [`/api/posts/${id}`] as const;
};

export const getGetApiPostsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    | GetApiPostsId400
    | GetApiPostsId401
    | GetApiPostsId404
    | GetApiPostsId500,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPostsId>>> = ({
    signal,
  }) => getApiPostsId(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getApiPostsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPostsId>>
>;
export type GetApiPostsIdQueryError =
  | GetApiPostsId400
  | GetApiPostsId401
  | GetApiPostsId404
  | GetApiPostsId500;

export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    | GetApiPostsId400
    | GetApiPostsId401
    | GetApiPostsId404
    | GetApiPostsId500,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    | GetApiPostsId400
    | GetApiPostsId401
    | GetApiPostsId404
    | GetApiPostsId500,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiPostsId>>,
          TError,
          Awaited<ReturnType<typeof getApiPostsId>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    | GetApiPostsId400
    | GetApiPostsId401
    | GetApiPostsId404
    | GetApiPostsId500,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get post by ID
 */

export function useGetApiPostsId<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    | GetApiPostsId400
    | GetApiPostsId401
    | GetApiPostsId404
    | GetApiPostsId500,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getApiPostsId>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}

export const getGetApiPostsIdSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    | GetApiPostsId400
    | GetApiPostsId401
    | GetApiPostsId404
    | GetApiPostsId500,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetApiPostsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiPostsId>>> = ({
    signal,
  }) => getApiPostsId(id, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getApiPostsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiPostsIdSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getApiPostsId>>
>;
export type GetApiPostsIdSuspenseQueryError =
  | GetApiPostsId400
  | GetApiPostsId401
  | GetApiPostsId404
  | GetApiPostsId500;

export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    | GetApiPostsId400
    | GetApiPostsId401
    | GetApiPostsId404
    | GetApiPostsId500,
>(
  id: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    | GetApiPostsId400
    | GetApiPostsId401
    | GetApiPostsId404
    | GetApiPostsId500,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    | GetApiPostsId400
    | GetApiPostsId401
    | GetApiPostsId404
    | GetApiPostsId500,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get post by ID
 */

export function useGetApiPostsIdSuspense<
  TData = Awaited<ReturnType<typeof getApiPostsId>>,
  TError =
    | GetApiPostsId400
    | GetApiPostsId401
    | GetApiPostsId404
    | GetApiPostsId500,
>(
  id: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getApiPostsId>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetApiPostsIdSuspenseQueryOptions(id, options);

  const query = useSuspenseQuery(
    queryOptions,
    queryClient,
  ) as UseSuspenseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Update a post when it is owned by the authenticated user.
 * @summary Update current user's post
 */
export const getPutApiPostsIdUrl = (id: number) => {
  return `/api/posts/${id}`;
};

export const putApiPostsId = async (
  id: number,
  internalInterfaceControllersUpdatePostRequest: InternalInterfaceControllersUpdatePostRequest,
  options?: RequestInit,
): Promise<void> => {
  return customInstance<void>(getPutApiPostsIdUrl(id), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(internalInterfaceControllersUpdatePostRequest),
  });
};

export const getPutApiPostsIdMutationOptions = <
  TError =
    | PutApiPostsId400
    | PutApiPostsId401
    | PutApiPostsId404
    | PutApiPostsId500,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putApiPostsId>>,
    TError,
    { id: number; data: InternalInterfaceControllersUpdatePostRequest },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putApiPostsId>>,
  TError,
  { id: number; data: InternalInterfaceControllersUpdatePostRequest },
  TContext
> => {
  const mutationKey = ["putApiPostsId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putApiPostsId>>,
    { id: number; data: InternalInterfaceControllersUpdatePostRequest }
  > = (props) => {
    const { id, data } = props ?? {};

    return putApiPostsId(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutApiPostsIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putApiPostsId>>
>;
export type PutApiPostsIdMutationBody =
  InternalInterfaceControllersUpdatePostRequest;
export type PutApiPostsIdMutationError =
  | PutApiPostsId400
  | PutApiPostsId401
  | PutApiPostsId404
  | PutApiPostsId500;

/**
 * @summary Update current user's post
 */
export const usePutApiPostsId = <
  TError =
    | PutApiPostsId400
    | PutApiPostsId401
    | PutApiPostsId404
    | PutApiPostsId500,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putApiPostsId>>,
      TError,
      { id: number; data: InternalInterfaceControllersUpdatePostRequest },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putApiPostsId>>,
  TError,
  { id: number; data: InternalInterfaceControllersUpdatePostRequest },
  TContext
> => {
  return useMutation(getPutApiPostsIdMutationOptions(options), queryClient);
};
