// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/domain/repositories/like.go
//
// Generated by this command:
//
//	mockgen -source=./internal/domain/repositories/like.go -destination=./internal/usecase/services/mocks/mock_like_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	models "Threadly/internal/domain/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPostLikeRepository is a mock of PostLikeRepository interface.
type MockPostLikeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostLikeRepositoryMockRecorder
	isgomock struct{}
}

// MockPostLikeRepositoryMockRecorder is the mock recorder for MockPostLikeRepository.
type MockPostLikeRepositoryMockRecorder struct {
	mock *MockPostLikeRepository
}

// NewMockPostLikeRepository creates a new mock instance.
func NewMockPostLikeRepository(ctrl *gomock.Controller) *MockPostLikeRepository {
	mock := &MockPostLikeRepository{ctrl: ctrl}
	mock.recorder = &MockPostLikeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostLikeRepository) EXPECT() *MockPostLikeRepositoryMockRecorder {
	return m.recorder
}

// CountByPostIDs mocks base method.
func (m *MockPostLikeRepository) CountByPostIDs(ctx context.Context, postIDs []models.UUID) (map[models.UUID]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByPostIDs", ctx, postIDs)
	ret0, _ := ret[0].(map[models.UUID]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByPostIDs indicates an expected call of CountByPostIDs.
func (mr *MockPostLikeRepositoryMockRecorder) CountByPostIDs(ctx, postIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByPostIDs", reflect.TypeOf((*MockPostLikeRepository)(nil).CountByPostIDs), ctx, postIDs)
}

// Delete mocks base method.
func (m *MockPostLikeRepository) Delete(ctx context.Context, userID, postID models.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPostLikeRepositoryMockRecorder) Delete(ctx, userID, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostLikeRepository)(nil).Delete), ctx, userID, postID)
}

// DeleteByPostID mocks base method.
func (m *MockPostLikeRepository) DeleteByPostID(ctx context.Context, postID models.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPostID", ctx, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPostID indicates an expected call of DeleteByPostID.
func (mr *MockPostLikeRepositoryMockRecorder) DeleteByPostID(ctx, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPostID", reflect.TypeOf((*MockPostLikeRepository)(nil).DeleteByPostID), ctx, postID)
}

// Ensure mocks base method.
func (m *MockPostLikeRepository) Ensure(ctx context.Context, userID, postID models.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ensure", ctx, userID, postID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ensure indicates an expected call of Ensure.
func (mr *MockPostLikeRepositoryMockRecorder) Ensure(ctx, userID, postID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ensure", reflect.TypeOf((*MockPostLikeRepository)(nil).Ensure), ctx, userID, postID)
}

// FindLikedPostIDs mocks base method.
func (m *MockPostLikeRepository) FindLikedPostIDs(ctx context.Context, userID models.UUID, postIDs []models.UUID) (map[models.UUID]struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLikedPostIDs", ctx, userID, postIDs)
	ret0, _ := ret[0].(map[models.UUID]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLikedPostIDs indicates an expected call of FindLikedPostIDs.
func (mr *MockPostLikeRepositoryMockRecorder) FindLikedPostIDs(ctx, userID, postIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLikedPostIDs", reflect.TypeOf((*MockPostLikeRepository)(nil).FindLikedPostIDs), ctx, userID, postIDs)
}

// MockCommentLikeRepository is a mock of CommentLikeRepository interface.
type MockCommentLikeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommentLikeRepositoryMockRecorder
	isgomock struct{}
}

// MockCommentLikeRepositoryMockRecorder is the mock recorder for MockCommentLikeRepository.
type MockCommentLikeRepositoryMockRecorder struct {
	mock *MockCommentLikeRepository
}

// NewMockCommentLikeRepository creates a new mock instance.
func NewMockCommentLikeRepository(ctrl *gomock.Controller) *MockCommentLikeRepository {
	mock := &MockCommentLikeRepository{ctrl: ctrl}
	mock.recorder = &MockCommentLikeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentLikeRepository) EXPECT() *MockCommentLikeRepositoryMockRecorder {
	return m.recorder
}

// CountByCommentIDs mocks base method.
func (m *MockCommentLikeRepository) CountByCommentIDs(ctx context.Context, commentIDs []models.UUID) (map[models.UUID]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCommentIDs", ctx, commentIDs)
	ret0, _ := ret[0].(map[models.UUID]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCommentIDs indicates an expected call of CountByCommentIDs.
func (mr *MockCommentLikeRepositoryMockRecorder) CountByCommentIDs(ctx, commentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCommentIDs", reflect.TypeOf((*MockCommentLikeRepository)(nil).CountByCommentIDs), ctx, commentIDs)
}

// Delete mocks base method.
func (m *MockCommentLikeRepository) Delete(ctx context.Context, userID, commentID models.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, commentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentLikeRepositoryMockRecorder) Delete(ctx, userID, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentLikeRepository)(nil).Delete), ctx, userID, commentID)
}

// DeleteByCommentIDs mocks base method.
func (m *MockCommentLikeRepository) DeleteByCommentIDs(ctx context.Context, commentIDs []models.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByCommentIDs", ctx, commentIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByCommentIDs indicates an expected call of DeleteByCommentIDs.
func (mr *MockCommentLikeRepositoryMockRecorder) DeleteByCommentIDs(ctx, commentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByCommentIDs", reflect.TypeOf((*MockCommentLikeRepository)(nil).DeleteByCommentIDs), ctx, commentIDs)
}

// Ensure mocks base method.
func (m *MockCommentLikeRepository) Ensure(ctx context.Context, userID, commentID models.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ensure", ctx, userID, commentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ensure indicates an expected call of Ensure.
func (mr *MockCommentLikeRepositoryMockRecorder) Ensure(ctx, userID, commentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ensure", reflect.TypeOf((*MockCommentLikeRepository)(nil).Ensure), ctx, userID, commentID)
}

// FindLikedCommentIDs mocks base method.
func (m *MockCommentLikeRepository) FindLikedCommentIDs(ctx context.Context, userID models.UUID, commentIDs []models.UUID) (map[models.UUID]struct{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLikedCommentIDs", ctx, userID, commentIDs)
	ret0, _ := ret[0].(map[models.UUID]struct{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLikedCommentIDs indicates an expected call of FindLikedCommentIDs.
func (mr *MockCommentLikeRepositoryMockRecorder) FindLikedCommentIDs(ctx, userID, commentIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLikedCommentIDs", reflect.TypeOf((*MockCommentLikeRepository)(nil).FindLikedCommentIDs), ctx, userID, commentIDs)
}
