receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  attributes/drop-db-query-text:
    actions:
      - key: db.query.text
        action: delete
      - key: db.statement
        action: delete
  batch: {}

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes/drop-db-query-text, batch]
      exporters: [otlp/tempo]
